# Generated by Django 2.0.3 on 2018-03-08 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trial', '0002_auto_20180308_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='role_fk',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='account_fk',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='account_fk',
        ),
        migrations.AddField(
            model_name='patient',
            name='user_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
