# Generated by Django 2.0.3 on 2018-03-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0004_remove_doctor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='selling',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
