# Generated by Django 2.0.3 on 2018-03-17 21:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0005_auto_20180309_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked', models.DateTimeField(default=datetime.datetime(2018, 3, 17, 21, 46, 13, 829073, tzinfo=utc))),
                ('last_reported', models.DateField(blank=True)),
                ('last_product_info', models.DateField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('warning', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NotSentMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.TextField()),
                ('send_error', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_email', models.EmailField(default='neuronmedical@gmail.com', max_length=254)),
                ('report_frequency', models.IntegerField(default=7)),
                ('report_on', models.BooleanField(default=True)),
                ('product_info_email', models.EmailField(blank=True, max_length=254)),
                ('product_info_frequency', models.IntegerField(default=1)),
                ('product_info_on', models.BooleanField(default=True)),
                ('critcal_product_amount', models.IntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
