# Generated by Django 2.0.3 on 2018-03-22 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0006_globalchecker_notification_notsentmail_siteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalchecker',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 12, 39, 53, 751214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='globalchecker',
            name='last_product_info',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='globalchecker',
            name='last_reported',
            field=models.DateField(null=True),
        ),
    ]
