# Generated by Django 2.0.3 on 2018-03-22 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0007_auto_20180322_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalchecker',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 14, 41, 48, 209110, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='globalchecker',
            name='last_product_info',
            field=models.DateField(default=datetime.date(1990, 1, 1)),
        ),
        migrations.AlterField(
            model_name='globalchecker',
            name='last_reported',
            field=models.DateField(default=datetime.date(1990, 1, 1)),
        ),
    ]
