# Generated by Django 2.0.3 on 2018-03-22 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0008_auto_20180322_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='critcal_product_amount',
            new_name='critical_product_amount',
        ),
        migrations.AlterField(
            model_name='globalchecker',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 17, 54, 33, 395108, tzinfo=utc)),
        ),
    ]
