# Generated by Django 2.0.3 on 2018-03-27 06:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0009_auto_20180322_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='globalchecker',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 27, 6, 28, 3, 319306, tzinfo=utc)),
        ),
    ]
