# Generated by Django 2.0.3 on 2018-03-27 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0010_auto_20180327_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalchecker',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 27, 6, 54, 18, 144601, tzinfo=utc)),
        ),
    ]
