# Generated by Django 2.0.3 on 2018-03-27 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0011_auto_20180327_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalchecker',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 27, 7, 49, 8, 782963, tzinfo=utc)),
        ),
    ]
