# Generated by Django 2.0.3 on 2018-03-29 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0012_auto_20180327_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='tracking_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='globalchecker',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 7, 59, 47, 490638, tzinfo=utc)),
        ),
    ]
