# Generated by Django 2.0.3 on 2018-03-30 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0013_auto_20180329_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='addit_phone',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='globalchecker',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 12, 41, 6, 194721, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
