# Generated by Django 2.0.3 on 2018-03-30 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0014_auto_20180330_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalchecker',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 12, 42, 56, 515920, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='addit_phone',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
