# Generated by Django 2.0.3 on 2018-03-30 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0015_auto_20180330_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalchecker',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 13, 43, 15, 67167, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='addit_phone',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
