# Generated by Django 2.0.3 on 2018-03-30 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0016_auto_20180330_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalchecker',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 14, 40, 59, 459580, tzinfo=utc)),
        ),
    ]
