# Generated by Django 2.0.3 on 2018-04-02 23:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0019_auto_20180403_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalchecker',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 23, 59, 54, 664067, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
