# Generated by Django 2.0.3 on 2018-04-05 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0020_auto_20180403_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='comission',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='discount_threshold',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='discount_value',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='globalchecker',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
