# Generated by Django 2.0.3 on 2018-04-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0021_auto_20180405_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='discount_threshold',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='discount_value',
        ),
    ]
