# Generated by Django 2.0.3 on 2018-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0022_auto_20180405_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='comission',
            field=models.IntegerField(default=10),
        ),
    ]
