# Generated by Django 2.0.3 on 2018-04-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0023_auto_20180405_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
