# Generated by Django 2.0.3 on 2018-04-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0025_order_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='seen',
            new_name='completed',
        ),
    ]
