# Generated by Django 2.0.3 on 2018-04-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0026_auto_20180405_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='product_image',
            field=models.FilePathField(default=None, null=True),
        ),
    ]
