# Generated by Django 2.0.3 on 2018-04-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0027_drug_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalchecker',
            name='new_orders',
            field=models.BooleanField(default=False),
        ),
    ]
